Repository Worksut/luc, pull requests merged in 2022-02, with the labels that each got.

#7 FEATURE: FEND-09 Title component
  package-lock.json
  package.json
  src/components/LogoTitle/LogoTitle.tsx
  src/components/LogoTitle/LogoTitleStyled.ts
  src/index.tsx
  src/sample/SampleView.tsx
Labels: feature, ready-to-merge

#9 FEATURE: FEND-09 Text component (#7)
  package-lock.json
  package.json
  src/components/Input/Input.tsx
  src/components/Input/InputStyled.ts
  src/components/LogoTitle/LogoTitleStyled.ts
  src/components/ProgressBar/ProgressBarStyle.ts
  src/components/Scrollable/Scrollable.tsx
  src/components/Scrollable/ScrollableStyle.ts
  src/components/SocialSection/SocialIcon/SocialIcon.tsx
  src/components/SocialSection/SocialSection.tsx
  src/components/Text/Text.tsx
  src/components/Text/TextStyled.ts
  src/sample/SampleView.scss
  src/sample/SampleView.tsx
  src/services/Settings/Settings.Styler.ts
  src/static/Colors.ts
  src/static/fonts/fonts.d.ts
  tsconfig.json
Labels: feature, ready-to-merge

#8 FEATURE: FEND-13 Tokens component
  src/components/Input/Input.tsx
  src/components/Input/InputStyled.ts
  src/components/Scrollable/ScrollableStyle.ts
  src/components/SocialSection/SocialSectionStyle.ts
  src/components/Wrapper/WrapperStyled.ts
  src/index.tsx
  src/sample/SampleView.scss
  src/sample/SampleView.tsx
  src/static/Colors.ts
Labels: feature, ready-to-merge

#10 FEATURE: FEND 15 Create Subview 2
  src/components/Scrollable/ScrollableStyle.ts
  src/components/Text/Text.tsx
  src/components/Text/TextStyled.ts
  src/sample/SampleView.scss
  src/sample/SampleView.tsx
  src/static/Colors.ts
  src/views/app/Slide-2/Slide-2.tsx
  src/views/app/Slide-2/SlideStyled-2.ts
Labels: feature, ready-to-merge

#14 FEATURE: FEND 19 Fix tokens and Fonts
  package-lock.json
  src/components/Input/InputStyled.ts
  src/components/LogoTitle/LogoTitleStyled.ts
  src/components/ProgressBar/ProgressBarStyle.ts
  src/components/Scrollable/ScrollableStyle.ts
  src/sample/SampleView.tsx
  src/static/Colors.ts
  src/static/Tokens.ts
  src/static/fonts/GothamMedium.ttf
  src/static/fonts/fonts.d.ts
  src/views/app/Slide-2/Slide-2.tsx
Labels: feature, ready-to-merge

#15 FEATURE: FEND-16 Create spinner component
  src/components/Counter/Counter.tsx
  src/components/Counter/CounterStyled.ts
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/SpinnerStyled.ts
  src/sample/SampleView.tsx
Labels: feature, ready-to-merge

#20 FEATURE: FEND-24 Fix tokens and views sizing
  src/components/Counter/Counter.tsx
  src/components/Input/InputStyled.ts
  src/components/Label/Label.tsx
  src/components/Label/LabelStyled.ts
  src/components/LogoTitle/LogoTitle.tsx
  src/components/LogoTitle/LogoTitleStyled.ts
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ProgressBar/ProgressBarStyle.ts
  src/components/Scrollable/ScrollableStyle.ts
  src/components/SocialSection/SocialIcon/SocialIcon.tsx
  src/components/SocialSection/SocialIcon/SocialIconStyle.ts
  src/components/SocialSection/SocialSectionStyle.ts
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/SpinnerStyled.ts
  src/sample/SampleView.tsx
  src/static/Tokens.ts
  src/static/img/social/instagram.png
  src/static/img/social/linkedin.png
  src/static/img/social/twitter.png
  src/views/app/Slide-1/Slide-1.tsx
  src/views/app/Slide-1/SlideStyled-1.ts
  src/views/app/Slide-2/SlideStyled-2.ts
Labels: feature, in review

#19 FEATURE: FEND-23 Create 4th view
  src/sample/SampleView.tsx
  src/static/Tokens.ts
  src/views/app/Slide-1/Slide-1.tsx
  src/views/app/Slide-4/Slide-4.tsx
  src/views/app/Slide-4/SlideStyled-4.ts
Labels: dont-merge, feature, work-in-progress

#12 FEATURE: FEND-18 Create Subview 3
  src/components/LogoTitle/LogoTitleStyled.ts
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ProgressBar/ProgressBarStyle.ts
  src/components/Scrollable/Scrollable.tsx
  src/components/Scrollable/ScrollableStyle.ts
  src/components/SocialSection/SocialIcon/SocialIconStyle.ts
  src/components/SocialSection/SocialSectionStyle.ts
  src/components/Text/Text.tsx
  src/components/Text/TextStyled.ts
  src/sample/SampleView.scss
  src/sample/SampleView.tsx
  src/static/Tokens.ts
  src/views/app/Slide-3/Slide-3.tsx
  src/views/app/Slide-3/SlideStyled-3.ts
  src/views/app/Slide-4/Slide-4.tsx
  src/views/app/Slide-5/Slide-5.tsx
  src/views/app/Slide-5/SlideStyled-5.ts
  src/views/app/Slide-6/Slide-6.tsx
  src/views/app/Slide-6/SlideStyled-6.ts
Labels: dont-merge, feature, work-in-progress
